---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - sts:AssumeRole
          Principal:
            Service: codepipeline.amazonaws.com
      Path: /
      Policies:
      - PolicyName: CodePipelinePolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - codebuild:*
            - codecommit:GitPull
            - s3:GetObject
            - s3:GetObjectVersion
            - s3:PutObject
            Resource: '*'
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      Name: MyCodePipeline
      Stages:
      - Name: Source
        Actions:
        - Name: SourceAction
          ActionTypeId:
            Category: Source
            Owner: AWS
            Version: '1'
            Provider: CodeCommit
          Configuration:
            RepositoryName: test
            BranchName: master
          OutputArtifacts:
            - Name: SourceArtifact
          RunOrder: 1
      - Name: Build
        Actions:
        - Name: BuildAction
          ActionTypeId:
            Category: Build
            Owner: AWS
            Version: '1'
            Provider: CodeBuild
          Configuration:
            ProjectName: MyCodeBuildProject
          InputArtifacts:
            - Name: SourceArtifact
          OutputArtifacts:
            - Name: BuildArtifact
          RunOrder: 2
      ArtifactStore:
        Type: S3
        Location: cf-templates-1v9qxypuhi229-ap-northeast-1
