# Define the pipeline
stages:
  - build
  - test
  - sonarcloud

# Define the build stage
build:
  stage: build
  image: maven:3-jdk-11
  script:
    - mvn clean package -B

# Define the test stage
test:
  stage: test
  image: maven:3-jdk-11
  script:
    - mvn test

# Define the SonarCloud integration stage
sonarcloud:
  stage: sonarcloud
  image: sonarsource/sonar-scanner-cli:4.6
  variables:
    SONAR_TOKEN: <your-sonarcloud-token>
  script:
    - sonar-scanner
