stages:
  - fetch_gcs_details

fetch_gcs_details:
  stage: fetch_gcs_details
  script:
    - gsutil ls gs://${GCS_BUCKET_NAME}/${GCS_OBJECT_NAME}



https://docs.google.com/document/d/1PgP-_flPciOObjEljnmtLhQduU6DmqU53D7B-n26V20/edit
